name: Linting, testing && building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    pipline:
        runs-on: windows-2019
        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: Installing modules
              run: npm install

            - name: Building production project
              run: npm run build:prod
              if: always()

            - name: Linting typescript
              run: npm run lint:ts
              if: always()

            - name: Linting styles
              run: npm run lint:scss
              if: always()

            - name: Unit testing
              run: npm run test:unit
              if: always()

            - name: Building storybook
              run: npm run build:sb
              if: always()

            - name: Screenshot testing
              run: npm run test:ui:ci
              if: always()
